### ISSUE TITLE
CORS error trying to load navbar + footer in Chrome

### ISSUE THREAD

**Issue by jksaunders** [Doze-Zoze/garreg-mach-library#1]
Looks like we'll have to find a different way to load in the navbar and footer.

![image](https://user-images.githubusercontent.com/5845037/132961235-b3e53a4b-25cb-405c-873d-0a5db49b2841.png)

**Comment by Doze-Zoze** [comment]
This error only comes up when opening the HTML file directly, as it doesn't properly load JQuery (i think?) but when opened in the published site or through something like the Five Server addon in Visual Studio Code (runs the site on your local network for modifying), it seems to load properly (by my testing at least) with no errors.

**Comment by jksaunders** [comment]
Oh great, never mind then!
